<a href="https://colab.research.google.com/github/jcjimenezb123/ProgramacionPython/blob/master/04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

**Numpy** es una biblioteca de Python específica para trabajar con arreglos, también tiene funciones de álgebral lineal, transformadas de Fourier y operaciones con matrices.

NumPy fue creado en 2005 por Travis Oliphant. Es un proyecto de código abierto que se puede usar libremente.

NumPy es un estándar para Python numérico.

Las operaciones con listas en Python son muy lentas, el objetivo de numpy es proveer de objetos mucho más rápidos.

NumPy almacena los arreglos en lugares continuos dentro de la memoria a diferencia de las listas, por lo tanto pueden ser accesadas y manipuladas de manera más eficiente.

NumPy está escrito parcialment en Python pero las partes que requieren su manipulación rápida está escrita en C y C++.

Para hacer uso de numpy primero se debe instalar y luego importar al ambiente de trabajo.

In [4]:
lista=list(range(10000000))
%timeit sum(lista)

10 loops, best of 3: 53.7 ms per loop


In [5]:
import numpy as np
vector=np.array(lista)
%timeit np.sum(vector)

100 loops, best of 3: 9.83 ms per loop


In [6]:
53.7/9.83

5.462868769074262

In [7]:
a=[1,2,3,4]
b=[10,11,12,13]
a+b

[1, 2, 3, 4, 10, 11, 12, 13]

In [8]:
suma=[]
for dato1,dato2 in zip(a,b):
  suma.append(dato1+dato2)
print(suma)

[11, 13, 15, 17]


In [13]:
x=np.array(a)
y=np.array(b)
print(x+y)
print(x-y)
print(x*y)
print(x@y)

[11 13 15 17]
[-9 -9 -9 -9]
[10 22 36 52]
120


In [16]:
a = np.array(1)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
e = np.array([1, 2, 3, 4], ndmin=5)

print(e)
print('number of dimensions :', e.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
x=np.array([1,2,3,4,-5,-6,-7,-8])
print(x)

[ 1  2  3  4 -5 -6 -7 -8]


In [ ]:
print('tipo de dato',x.dtype)
print('forma ',x.shape)
print('tamano ',x.size)
print('dimensiones ',x.ndim)
print('tamano de cada elemento ',x.itemsize)
print('memoria usada ',x.nbytes)

tipo de dato int64
forma  (8,)
tamano  8
dimensiones  1
tamano de cada elemento  8
memoaria usada  64


In [ ]:
print(x[0])

1


In [ ]:
print(x[1])

2


In [ ]:
print(x.__getitem__(1))

2


In [ ]:
print(x[-1])

-8


In [ ]:
print(x[-2])

-7


In [ ]:
print(x[-2:])

[-7 -8]


In [ ]:
print(x[1:3])

[2 3]


In [ ]:
print(x[:3])

[1 2 3]


In [ ]:
x[0]=3.1416
print(x)

[ 3  2  3  4 -5 -6 -7 -8]


In [ ]:
x=np.array([0 if valor<0 else valor for valor in x ])
print(x)

[3 2 3 4 0 0 0 0]


In [ ]:
complejos=np.array([1+2j,3,4-2.1j])
print(complejos)
print(complejos.dtype)

[1.+2.j  3.+0.j  4.-2.1j]
complex128


In [ ]:
y=np.array([1,2,3.1416,4])
print(y)
print(y.dtype)


[1.     2.     3.1416 4.    ]
float64


In [ ]:
y[1]=2.7172
print(y)

[1.     2.7172 3.1416 4.    ]


In [ ]:
xx=np.array([1,2,3,4],dtype=float)
print(xx)
print(xx.dtype)

[1. 2. 3. 4.]
float64


In [ ]:
xx[2]=3.1416
print(xx)

[1.     2.     3.1416 4.    ]


In [ ]:
xx.__setitem__(1,2.7172)
print(xx)

[1.     2.7172 3.1416 4.    ]


In [ ]:
xx[0]=1.4142
print(xx)

[1.4142 2.7172 3.1416 4.    ]


In [ ]:
z=x+y
print(z)

[2.     4.7172 6.1416 8.    ]


In [ ]:
z=x/y
print(z)

[1.         0.73605182 0.95492743 1.        ]


In [ ]:
z=x*y
print(z)

[ 1.      5.4344  9.4248 16.    ]


In [ ]:
z=x**y
print(z)

[  1.           6.57595306  31.54453529 256.        ]


In [ ]:
s=np.sin(x)
print(s)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
x10=x*10
print(x10)

[10 20 30 40]


In [ ]:
x_10=x-10
print(x_10)

[-9 -8 -7 -6]


In [ ]:
indices=[0,2,3]
print(x[indices])

[1 3 4]


In [ ]:
arreglo=np.array([-2,-3,0,1,-1,4,-10,3])
negativos=arreglo<0
print(negativos)

[ True  True False False  True False  True False]


In [ ]:
print(arreglo[negativos])

[ -2  -3  -1 -10]


In [ ]:
arreglo[negativos]=0
print(arreglo)

[0 0 0 1 0 4 0 3]


In [19]:
x=np.array([-2,-4,-1,0,2,4,8,-9])
print('x=',x)
print('suma ',x.sum() )
print('suma acumulada',x.cumsum())
print('producto ',x.prod() )
print('producto ',x.cumprod() )
print('maximo ',x.max() )
print('minimo ',x.min() )
print('desviasion estandar ',x.std() )
print('varianza ',x.var() )
print('promedio ',x.mean( ) )

x= [-2 -4 -1  0  2  4  8 -9]
suma  -2
suma acumulada [-2 -6 -7 -7 -5 -1  7 -2]
producto  0
producto  [-2  8 -8  0  0  0  0  0]
maximo  8
minimo  -9
desviasion estandar  4.815340071064556
varianza  23.1875
promedio  -0.25


In [20]:
print('suma positivos ',x.sum(where=x>0) )
print('suma negativos ',x.sum(where=x<0) )
print('desviacion positivos ',np.array([v for v in x if v>0]).std() )
print('promedio positivos ',np.array([v for v in x if v>0]).mean() )

suma positivos  14
suma negativos  -16
desviacion positivos  2.494438257849294
promedio positivos  4.666666666666667


In [21]:
p_max=np.where(x==x.max())
print(p_max)
print(x[p_max])

(array([6]),)
[8]


In [22]:
y=x
y[0]=-100
print(x)
print(y)

[-100   -4   -1    0    2    4    8   -9]
[-100   -4   -1    0    2    4    8   -9]


In [23]:
copiax=x.copy()
copiax[0]=200
print(x)
print(copiax)

[-100   -4   -1    0    2    4    8   -9]
[200  -4  -1   0   2   4   8  -9]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.flatten()

print(newarr)

[1 2 3 4 5 6]


In [30]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
i=0
for x in arr:
  i+=1
  print(i,x)

1 [1 2 3]
2 [4 5 6]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
i=0
for x in arr:
  i+=1
  print(i,x)

1 [[1 2 3]
 [4 5 6]]
2 [[ 7  8  9]
 [10 11 12]]


In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [37]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8



Juntar significa colocar el contenido de dos o mas arreglos en un arreglo simple

In [38]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [46]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

abajo = np.concatenate((arr1, arr2), axis=0)
al_lado = np.concatenate((arr1, arr2), axis=1)
print(abajo)
print()
print(al_lado)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [40]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [48]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [49]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [51]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [52]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [53]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [54]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [57]:
from numpy import random

x = random.randint(100)

print(x)

45


In [59]:
x=random.randint(100, size=(5))

print(x)

[32 84 38 20 37]


In [60]:
x = random.randint(100, size=(3, 5))

print(x)

[[22 30 86 86 57]
 [70 49 32 15 41]
 [50 85 93  1 15]]


In [58]:
x = random.rand()

print(x)

0.16253375476398613


In [61]:
x = random.rand(5)

print(x)

[0.82374832 0.37672948 0.25168734 0.53854614 0.72780458]


In [62]:
x = random.rand(3, 5)

print(x)

[[0.57986346 0.82961761 0.13575936 0.24230378 0.01678805]
 [0.51502128 0.28753477 0.54160107 0.9541157  0.63042028]
 [0.3353144  0.92771725 0.24403812 0.1493946  0.63918891]]


In [63]:
x = random.choice([3, 5, 7, 9]) #retorna uno de los 4 valores

print(x)

3


In [64]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 3 5 3]
 [5 7 3 9 7]
 [3 7 5 7 9]]


In [66]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100)) #retorna uno de los valores con la probabilidad indicada para cada digito

print(x)

[7 7 5 5 7 7 5 7 7 7 5 3 7 7 5 7 5 7 7 7 7 5 7 3 7 3 7 5 3 5 7 5 5 5 7 5 5
 5 7 7 7 7 5 7 7 5 7 7 5 5 7 7 7 5 7 7 3 5 7 7 7 7 7 7 5 7 7 5 7 7 5 7 7 7
 7 7 7 7 7 7 5 7 5 5 7 5 7 5 5 5 5 5 5 3 7 5 5 5 5 5]


In [67]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 5 7 5]
 [7 7 7 5 7]
 [7 5 7 7 7]]


In [68]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 3 1 5 4]


In [69]:
arr = np.array([1, 2, 3, 4, 5]) #Generate a random permutation of elements of following array

print(random.permutation(arr))

[4 3 5 1 2]
