<a href="https://colab.research.google.com/github/jcjimenezb123/ProgramacionPython/blob/master/04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

**Numpy** es una biblioteca de Python específica para trabajar con arreglos, también tiene funciones de álgebral lineal, transformadas de Fourier y operaciones con matrices.

NumPy fue creado en 2005 por Travis Oliphant. Es un proyecto de código abierto que se puede usar libremente.

NumPy es un estándar para Python numérico.

Las operaciones con listas en Python son muy lentas, el objetivo de numpy es proveer de objetos mucho más rápidos.

NumPy almacena los arreglos en lugares continuos dentro de la memoria a diferencia de las listas, por lo tanto pueden ser accesadas y manipuladas de manera más eficiente.

NumPy está escrito parcialment en Python pero las partes que requieren su manipulación rápida está escrita en C y C++.

Para hacer uso de numpy primero se debe instalar y luego importar al ambiente de trabajo.

In [ ]:
lista=list(range(10000000))
%timeit sum(lista)

10 loops, best of 3: 53.3 ms per loop


In [ ]:
import numpy as np
vector=np.array(lista)
%timeit np.sum(vector)

100 loops, best of 3: 9.66 ms per loop


In [ ]:
53.7/9.83

5.462868769074262

In [ ]:
a=[1,2,3,4]
b=[10,11,12,13]
a+b

[1, 2, 3, 4, 10, 11, 12, 13]

In [ ]:
suma=[]
for dato1,dato2 in zip(a,b):
  suma.append(dato1+dato2)
print(suma)

[11, 13, 15, 17]


In [ ]:
x=np.array(a)
y=np.array(b)
print(x+y)
print(x-y)
print(x*y)
print(x@y)

[11 13 15 17]
[-9 -9 -9 -9]
[10 22 36 52]
120


In [ ]:
a = np.array(1)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
e = np.array([1, 2, 3, 4], ndmin=5)

print(e)
print('number of dimensions :', e.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
x=np.array([1,2,3,4,-5,-6,-7,-8])
print(x)

[ 1  2  3  4 -5 -6 -7 -8]


In [ ]:
print('tipo de dato',x.dtype)
print('forma ',x.shape)
print('tamano ',x.size)
print('dimensiones ',x.ndim)
print('tamano de cada elemento ',x.itemsize)
print('memoria usada ',x.nbytes)

tipo de dato int64
forma  (8,)
tamano  8
dimensiones  1
tamano de cada elemento  8
memoaria usada  64


In [ ]:
print(x[0])

1


In [ ]:
print(x[1])

2


In [ ]:
print(x.__getitem__(1))

2


In [ ]:
print(x[-1])

-8


In [ ]:
print(x[-2])

-7


In [ ]:
print(x[-2:])

[-7 -8]


In [ ]:
print(x[1:3])

[2 3]


In [ ]:
print(x[:3])

[1 2 3]


In [ ]:
x[0]=3.1416
print(x)

[ 3  2  3  4 -5 -6 -7 -8]


In [ ]:
x=np.array([0 if valor<0 else valor for valor in x ])
print(x)

[3 2 3 4 0 0 0 0]


In [ ]:
x = np.empty([3,2], dtype=int)
print(x)

[[26525328        0]
 [       0        0]
 [       0        0]]


In [ ]:
x = np.zeros(5)
print( x)

[0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [ ]:
x = np.ones(5)
print( x)

[1. 1. 1. 1. 1.]


In [ ]:
x = np.ones(5)*np.pi
print (x)

[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]


In [ ]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [ ]:
x = np.arange(10,20,2,dtype=float)
print(x)

[10. 12. 14. 16. 18.]


In [ ]:
x = np.linspace(10,20)
print(x)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [ ]:
x = np.linspace(10,20,11)
print(x)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [ ]:
complejos=np.array([1+2j,3,4-2.1j])
print(complejos)
print(complejos.dtype)

[1.+2.j  3.+0.j  4.-2.1j]
complex128


In [ ]:
y=np.array([1,2,3.1416,4])
print(y)
print(y.dtype)


[1.     2.     3.1416 4.    ]
float64


In [ ]:
y[1]=2.7172
print(y)

[1.     2.7172 3.1416 4.    ]


In [ ]:
xx=np.array([1,2,3,4],dtype=float)
print(xx)
print(xx.dtype)

[1. 2. 3. 4.]
float64


In [ ]:
xx[2]=3.1416
print(xx)

[1.     2.     3.1416 4.    ]


In [ ]:
xx.__setitem__(1,2.7172)
print(xx)

[1.     2.7172 3.1416 4.    ]


In [ ]:
xx[0]=1.4142
print(xx)

[1.4142 2.7172 3.1416 4.    ]


In [ ]:
z=x+y
print(z)

[2.     4.7172 6.1416 8.    ]


In [ ]:
z=x/y
print(z)

[1.         0.73605182 0.95492743 1.        ]


In [ ]:
z=x*y
print(z)

[ 1.      5.4344  9.4248 16.    ]


In [ ]:
z=x**y
print(z)

[  1.           6.57595306  31.54453529 256.        ]


In [ ]:
s=np.sin(x)
print(s)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
x10=x*10
print(x10)

[10 20 30 40]


In [ ]:
x_10=x-10
print(x_10)

[-9 -8 -7 -6]


In [ ]:
indices=[0,2,3]
print(x[indices])

[1 3 4]


In [ ]:
arreglo=np.array([-2,-3,0,1,-1,4,-10,3])
negativos=arreglo<0
print(negativos)

[ True  True False False  True False  True False]


In [ ]:
print(arreglo[negativos])

[ -2  -3  -1 -10]


In [ ]:
arreglo[negativos]=0
print(arreglo)

[0 0 0 1 0 4 0 3]


In [ ]:
x=np.array([-2,-4,-1,0,2,4,8,-9])
print('x=',x)
print('suma ',x.sum() )
print('suma acumulada',x.cumsum())
print('producto ',x.prod() )
print('producto ',x.cumprod() )
print('maximo ',x.max() )
print('minimo ',x.min() )
print('desviasion estandar ',x.std() )
print('varianza ',x.var() )
print('promedio ',x.mean( ) )

x= [-2 -4 -1  0  2  4  8 -9]
suma  -2
suma acumulada [-2 -6 -7 -7 -5 -1  7 -2]
producto  0
producto  [-2  8 -8  0  0  0  0  0]
maximo  8
minimo  -9
desviasion estandar  4.815340071064556
varianza  23.1875
promedio  -0.25


In [ ]:
print('suma positivos ',x.sum(where=x>0) )
print('suma positivos ',x[x>0].sum() )

print('suma negativos ',x.sum(where=x<0) )
print('desviacion positivos ',x[x>0].std() )

print('promedio positivos ',x[x>0].mean() )

suma positivos  14
suma positivos  14
suma negativos  -16
desviacion positivos  2.494438257849294
promedio positivos  4.666666666666667


In [ ]:
p_max=np.where(x==x.max())
print(p_max)
print(x[p_max])

(array([6]),)
[8]


In [ ]:
x = np.array([np.nan, 1,2,np.nan,3,4,5])
print (x[~np.isnan(x)])

[1. 2. 3. 4. 5.]


In [ ]:
y=x
y[0]=-100
print(x)
print(y)

[-100   -4   -1    0    2    4    8   -9]
[-100   -4   -1    0    2    4    8   -9]


In [ ]:
copiax=x.copy()
copiax[0]=200
print(x)
print(copiax)

[-100   -4   -1    0    2    4    8   -9]
[200  -4  -1   0   2   4   8  -9]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.flatten()

print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
i=0
for x in arr:
  i+=1
  print(i,x)

1 [1 2 3]
2 [4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
i=0
for x in arr:
  i+=1
  print(i,x)

1 [[1 2 3]
 [4 5 6]]
2 [[ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8



Juntar significa colocar el contenido de dos o mas arreglos en un arreglo simple

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

abajo = np.concatenate((arr1, arr2), axis=0)
al_lado = np.concatenate((arr1, arr2), axis=1)
print(abajo)
print()
print(al_lado)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
from numpy import random

x = random.randint(100)

print(x)

45


In [ ]:
x=random.randint(100, size=(5))

print(x)

[32 84 38 20 37]


In [ ]:
x = random.randint(100, size=(3, 5))

print(x)

[[22 30 86 86 57]
 [70 49 32 15 41]
 [50 85 93  1 15]]


In [ ]:
x = random.rand()

print(x)

0.16253375476398613


In [ ]:
x = random.rand(5)

print(x)

[0.82374832 0.37672948 0.25168734 0.53854614 0.72780458]


In [ ]:
x = random.rand(3, 5)

print(x)

[[0.57986346 0.82961761 0.13575936 0.24230378 0.01678805]
 [0.51502128 0.28753477 0.54160107 0.9541157  0.63042028]
 [0.3353144  0.92771725 0.24403812 0.1493946  0.63918891]]


In [ ]:
x = random.choice([3, 5, 7, 9]) #retorna uno de los 4 valores

print(x)

3


In [ ]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 3 5 3]
 [5 7 3 9 7]
 [3 7 5 7 9]]


In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100)) #retorna uno de los valores con la probabilidad indicada para cada digito

print(x)

[7 7 5 5 7 7 5 7 7 7 5 3 7 7 5 7 5 7 7 7 7 5 7 3 7 3 7 5 3 5 7 5 5 5 7 5 5
 5 7 7 7 7 5 7 7 5 7 7 5 5 7 7 7 5 7 7 3 5 7 7 7 7 7 7 5 7 7 5 7 7 5 7 7 7
 7 7 7 7 7 7 5 7 5 5 7 5 7 5 5 5 5 5 5 3 7 5 5 5 5 5]


In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 5 7 5]
 [7 7 7 5 7]
 [7 5 7 7 7]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 3 1 5 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5]) #Generate a random permutation of elements of following array

print(random.permutation(arr))

[4 3 5 1 2]


In [ ]:
a = np.arange(12).reshape(3,4)
print ('The original array is:')
print (a)
print ('\n')
print ('Array after applying the function:')
print (a.T)

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array after applying the function:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
a = np.arange(9).reshape(3,3)
print ('The original array is:')
print (a)
print ('\n')
print ('Array after applying the function:')
print (np.swapaxes(a,1,0))

The original array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Array after applying the function:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [ ]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print ('Our array is:')
print (a)
print ('\n')
print ('Applying amin() function:')
print (np.amin(a))
print ('\n')
print ('Applying amin() function:')
print (np.amin(a,1))
print ('\n')
print ('Applying amin() function again:')
print (np.amin(a,0))
print ('\n')
print ('Applying amax() function:')
print (np.amax(a))
print ('\n')
print ('Applying amax() function again:')
print (np.amax(a, axis=0))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
2


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]


In [ ]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print ('Our array is:')
print (a)
print ('\n')
print ('Applying ptp() function:')
print (np.ptp(a))
print ('\n')
print ('Applying ptp() function along axis 1:')
print (np.ptp(a, axis=1))
print ('\n')
print ('Applying ptp() function along axis 0:')
print (np.ptp(a, axis=0))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying ptp() function:
7


Applying ptp() function along axis 1:
[4 5 7]


Applying ptp() function along axis 0:
[6 3 6]


In [ ]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])
print ('Our array is:')
print (a)
print ('\n')
print ('Applying median() function:')
print (np.median(a))
print ('\n')
print ('Applying median() function along axis 0:')
print (np.median(a, axis=0))
print ('\n')
print ('Applying median() function along axis 1:')
print (np.median(a, axis=1))

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Applying median() function:
65.0


Applying median() function along axis 0:
[50. 90. 60.]


Applying median() function along axis 1:
[65. 80. 60.]


In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print ('Our array is:')
print (a)
print ('\n')
print ('Applying mean() function:')
print (np.mean(a))
print ('\n')
print ('Applying mean() function along axis 0:')
print (np.mean(a, axis=0))
print ('\n')
print ('Applying mean() function along axis 1:')
print (np.mean(a, axis=1))

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 1:
[2. 4. 5.]


In [ ]:
a = np.array([1,2,3,4])
print ('Our array is:')
print (a)
print ('\n')
print ('Applying average() function:')
print (np.average(a))
print ('\n')
# this is same as mean when weight is not specified
wts=np.array([4,3,2,1])
print ('Applying average() function again:')
print (np.average(a,weights=wts))
print ('\n')
# Returns the sum of weights, if the returned parameter is set to True.
print ('Sum of weights')
print (np.average([1,2,3, 4],weights=[4,3,2,1], returned=True))

Our array is:
[1 2 3 4]


Applying average() function:
2.5


Applying average() function again:
2.0


Sum of weights
(2.0, 10.0)


In [ ]:
a = np.arange(6).reshape(3,2)
print ('Our array is:')
print (a)
print ('\n')
print ('Modified array:')
wt=np.array([3,5])
print (np.average(a, axis=1, weights=wt))
print ('\n')
print ('Modified array:')
print (np.average(a, axis=1, weights=wt, returned=True))

Our array is:
[[0 1]
 [2 3]
 [4 5]]


Modified array:
[0.625 2.625 4.625]


Modified array:
(array([0.625, 2.625, 4.625]), array([8., 8., 8.]))


In [ ]:
x=np.array([1,2,3,4])
print (np.std(x))
std = np.sqrt(np.mean(abs(x - x.mean())**2))
print(std)

1.118033988749895
1.118033988749895


In [ ]:
print (np.var([1,2,3,4]))

1.25


In [ ]:
a = np.array([[3,7],[9,1]])
print ('Our array is:')
print (a)
print ('\n')
print ('Applying sort() function:')
print (np.sort(a))
print ('\n')
print ('Sort along axis 0:')
print (np.sort(a, axis=0))
print ('\n')
# Order parameter in sort function
dt = np.dtype([('name', 'S10'),('age', int)])
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype=dt)
print ('Our array is:')
print (a)
print ('\n')
print ('Order by name:')
print (np.sort(a, order='name'))

Our array is:
[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Sort along axis 0:
[[3 1]
 [9 7]]


Our array is:
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


Order by name:
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [ ]:
x = np.arange(9.).reshape(3, 3)
print ('Our array is:')
print (x)
# define a condition
condition = np.mod(x,2)==0
print ('Element-wise value of condition')
print (condition)
print ('Extract elements using condition')
print (np.extract(condition, x))

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]
Extract elements using condition
[0. 2. 4. 6. 8.]


In [ ]:
# For 2-D array, it is matrix multiplication
import numpy.matlib
import numpy as np
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [ ]:
# 2-D mixed with 1-D
import numpy.matlib
import numpy as np
a=[[1,0],[0,1]]
b=[1,2]
print (np.matmul(a,b))
print (np.matmul(b,a))

[1 2]
[1 2]


In [ ]:
a = np.array([[1,2], [3,4]])
print (np.linalg.det(a))

-2.0000000000000004


In [ ]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
print ('Array a:')
print (a)
ainv=np.linalg.inv(a)
print ('Inverse of a:')
print (ainv)
print ('Matrix B is:')
b = np.array([[6],[-4],[27]])
print (b)
print ('Compute A-1B:')
print (np.matmul(ainv,b))
print ('solve:')
print (np.linalg.solve(a,b))

Array a:
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
Inverse of a:
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
Matrix B is:
[[ 6]
 [-4]
 [27]]
Compute A-1B:
[[ 5.]
 [ 3.]
 [-2.]]
solve:
[[ 5.]
 [ 3.]
 [-2.]]


In [ ]:
a=np.array([1,2,3,4,5])
np.save('var_a',a)

In [ ]:
b = np.load('var_a.npy')
print (b)

[1 2 3 4 5]


In [ ]:
a = np.array([1,2,3,4,5])
np.savetxt('a.txt',a)
b = np.loadtxt('a.txt')
print (b)

[1. 2. 3. 4. 5.]


In [ ]:
!cat a.txt

1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00


In [ ]:
!pip install mat4py

In [ ]:
from mat4py import savemat
a={'a':100}
savemat('datafile.mat', a)

In [ ]:
from mat4py import loadmat
data = loadmat('datafile.mat')
print(data)

{'a': 100}


In [ ]:
!pip install matlab

In [ ]:
import matlab

print(matlab.cos(np.pi))

x=np.array([1,2,3,4])
y=np.array([1,2,3,4])
xi=1.5
print(matlab.interp(xi,x,y))

-1.0
1.5
