<a href="https://colab.research.google.com/github/jcjimenezb123/ProgramacionPython/blob/master/04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

**Numpy** es una biblioteca de Python específica para trabajar con arreglos, también tiene funciones de álgebral lineal, transformadas de Fourier y operaciones con matrices.

NumPy fue creado en 2005 por Travis Oliphant. Es un proyecto de código abierto que se puede usar libremente.

NumPy es un estándar para Python numérico.

Las operaciones con listas en Python son muy lentas, el objetivo de numpy es proveer de objetos mucho más rápidos.

NumPy almacena los arreglos en lugares continuos dentro de la memoria a diferencia de las listas, por lo tanto pueden ser accesadas y manipuladas de manera más eficiente.

NumPy está escrito parcialment en Python pero las partes que requieren su manipulación rápida está escrita en C y C++.

Para hacer uso de numpy primero se debe instalar y luego importar al ambiente de trabajo.

In [2]:
import numpy as np

a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
lista=list(range(10000000))
%timeit sum(lista)

10 loops, best of 3: 53.3 ms per loop


In [ ]:
import numpy as np
vector=np.array(lista)
%timeit np.sum(vector)

100 loops, best of 3: 9.66 ms per loop


In [25]:
a=[1,2,3,4]
b=[10,11,12,13]
a+b

[1, 2, 3, 4, 10, 11, 12, 13]

In [ ]:
suma=[]
for dato1,dato2 in zip(a,b):
  suma.append(dato1+dato2)
print(suma)

[11, 13, 15, 17]


In [29]:
x=np.array(a)
y=np.array(b)
print(x+y)
print(x-y)
print(x*y)
print(x@y)

[11 13 15 17]
[-9 -9 -9 -9]
[10 22 36 52]
120


In [ ]:
a = np.array(1)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
e = np.array([1, 2, 3, 4], ndmin=5)

print(e)
print('number of dimensions :', e.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [2]:
x=np.array([1,2,3,4,-5,-6,-7,-8])
print(x)

[ 1  2  3  4 -5 -6 -7 -8]


In [3]:
print('tipo de dato',x.dtype)
print('forma ',x.shape)
print('tamano ',x.size)
print('dimensiones ',x.ndim)
print('tamano de cada elemento ',x.itemsize)
print('memoria usada ',x.nbytes)

tipo de dato int64
forma  (8,)
tamano  8
dimensiones  1
tamano de cada elemento  8
memoria usada  64


In [ ]:
print(x[0])

1


In [ ]:
print(x[1])

2


In [ ]:
print(x.__getitem__(1))

2


In [ ]:
print(x[-1])

-8


In [ ]:
print(x[-2])

-7


In [ ]:
print(x[-2:])

[-7 -8]


In [ ]:
print(x[1:3])

[2 3]


In [ ]:
print(x[:3])

[1 2 3]


In [ ]:
x[0]=3.1416
print(x)

[ 3  2  3  4 -5 -6 -7 -8]


In [6]:
x=np.array([0 if valor<0 else valor for valor in x ])
print(x)

[1 2 3 4 0 0 0 0]


In [ ]:
x = np.empty([3,2], dtype=int)
print(x)

[[26525328        0]
 [       0        0]
 [       0        0]]


In [ ]:
x = np.zeros(5)
print( x)

[0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [ ]:
x = np.ones(5)
print( x)

[1. 1. 1. 1. 1.]


In [ ]:
x = np.ones(5)*np.pi
print (x)

[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]


In [ ]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [3]:
x = np.arange(10,20,2,dtype=float)
print(x)

[10. 12. 14. 16. 18.]


In [ ]:
x = np.linspace(10,20)
print(x)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [ ]:
x = np.linspace(10,20,11)
print(x)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [ ]:
complejos=np.array([1+2j,3,4-2.1j])
print(complejos)
print(complejos.dtype)

[1.+2.j  3.+0.j  4.-2.1j]
complex128


In [ ]:
y=np.array([1,2,3.1416,4])
print(y)
print(y.dtype)


[1.     2.     3.1416 4.    ]
float64


In [ ]:
y[1]=2.7172
print(y)

[1.     2.7172 3.1416 4.    ]


In [ ]:
xx=np.array([1,2,3,4],dtype=float)
print(xx)
print(xx.dtype)

[1. 2. 3. 4.]
float64


In [ ]:
xx[2]=3.1416
print(xx)

[1.     2.     3.1416 4.    ]


In [ ]:
xx.__setitem__(1,2.7172)
print(xx)

[1.     2.7172 3.1416 4.    ]


In [ ]:
xx[0]=1.4142
print(xx)

[1.4142 2.7172 3.1416 4.    ]


In [ ]:
z=x+y
print(z)

[2.     4.7172 6.1416 8.    ]


In [ ]:
z=x/y
print(z)

[1.         0.73605182 0.95492743 1.        ]


In [ ]:
z=x*y
print(z)

[ 1.      5.4344  9.4248 16.    ]


In [ ]:
z=x**y
print(z)

[  1.           6.57595306  31.54453529 256.        ]


In [4]:
s=np.sin(x)
print(s)

[-0.54402111 -0.53657292  0.99060736 -0.28790332 -0.75098725]


In [5]:
s=np.cos(x)
print(s)

[-0.83907153  0.84385396  0.13673722 -0.95765948  0.66031671]


In [6]:
s=np.exp(x)
print(s)

[2.20264658e+04 1.62754791e+05 1.20260428e+06 8.88611052e+06
 6.56599691e+07]


In [7]:
s=np.log(x)
print(s)

[2.30258509 2.48490665 2.63905733 2.77258872 2.89037176]


In [8]:
s=np.log10(x)
print(s)

[1.         1.07918125 1.14612804 1.20411998 1.25527251]


In [9]:
s=np.arcsinh(x)
print(s)

[2.99822295 3.17978544 3.33347759 3.46671104 3.58428965]


In [10]:
s=np.sqrt(x)
print(s)

[3.16227766 3.46410162 3.74165739 4.         4.24264069]


In [ ]:
x10=x*10
print(x10)

[10 20 30 40]


In [ ]:
x_10=x-10
print(x_10)

[-9 -8 -7 -6]


In [ ]:
indices=[0,2,3]
print(x[indices])

[1 3 4]


In [ ]:
arreglo=np.array([-2,-3,0,1,-1,4,-10,3])
negativos=arreglo<0
print(negativos)

[ True  True False False  True False  True False]


In [ ]:
print(arreglo[negativos])

[ -2  -3  -1 -10]


In [ ]:
arreglo[negativos]=0
print(arreglo)

[0 0 0 1 0 4 0 3]


In [ ]:
x=np.array([-2,-4,-1,0,2,4,8,-9])
print('x=',x)
print('suma ',x.sum() )
print('suma acumulada',x.cumsum())
print('producto ',x.prod() )
print('producto ',x.cumprod() )
print('maximo ',x.max() )
print('minimo ',x.min() )
print('desviasion estandar ',x.std() )
print('varianza ',x.var() )
print('promedio ',x.mean( ) )

x= [-2 -4 -1  0  2  4  8 -9]
suma  -2
suma acumulada [-2 -6 -7 -7 -5 -1  7 -2]
producto  0
producto  [-2  8 -8  0  0  0  0  0]
maximo  8
minimo  -9
desviasion estandar  4.815340071064556
varianza  23.1875
promedio  -0.25


In [ ]:
print('suma positivos ',x.sum(where=x>0) )
print('suma positivos ',x[x>0].sum() )

print('suma negativos ',x.sum(where=x<0) )
print('desviacion positivos ',x[x>0].std() )

print('promedio positivos ',x[x>0].mean() )

suma positivos  14
suma positivos  14
suma negativos  -16
desviacion positivos  2.494438257849294
promedio positivos  4.666666666666667


In [ ]:
p_max=np.where(x==x.max())
print(p_max)
print(x[p_max])

(array([6]),)
[8]


In [ ]:
x = np.array([np.nan, 1,2,np.nan,3,4,5])
print (x[~np.isnan(x)])

[1. 2. 3. 4. 5.]


In [ ]:
y=x
y[0]=-100
print(x)
print(y)

[-100   -4   -1    0    2    4    8   -9]
[-100   -4   -1    0    2    4    8   -9]


In [2]:
import numpy as np
x=np.array([-2,-4,-1,0,2,4,8,-9])

copiax=x.copy()
copiax[0]=200
print(x)
print(copiax)

[-2 -4 -1  0  2  4  8 -9]
[200  -4  -1   0   2   4   8  -9]


Sistemas de ecuaciones lineales

$$
\begin{align}
2x + y − z &= 11\\
x − 3y &= −20\\
4x + 2y + 5z &= 8
\end{align}
$$

In [3]:
A=np.array([[2,1,-1],
            [1,-3,0],
            [4,2,5]])
b=np.array([[11,-20,8]])

In [22]:
Ab=np.concatenate((A,b.T),axis=1)
Ab

array([[  2,   1,  -1,  11],
       [  1,  -3,   0, -20],
       [  4,   2,   5,   8]])

In [23]:
np.linalg.matrix_rank(A)

3

In [24]:
np.linalg.matrix_rank(Ab)

3

In [30]:
solucion = np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A) == 3
solucion

True

In [9]:
np.linalg.det(A)

-49.000000000000014

In [6]:
np.linalg.solve(A,b.T)

array([[ 1.],
       [ 7.],
       [-2.]])

In [8]:
np.dot(np.linalg.inv(A),b.T)

array([[ 1.],
       [ 7.],
       [-2.]])

In [20]:
detA=np.linalg.det(A)
cols=np.size(A,axis=1)
x=np.zeros(cols)
for c in range(cols):
  Ac=A.copy()
  Ac[:,c]=b
  x[c]=np.linalg.det(Ac)/detA
  
print(x)

[ 1.  7. -2.]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.flatten()

print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


In [ ]:
arr.sort()
print(arr)

[0 1 2 3]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
print(arr)
arr.sort()
print(arr)

['apple' 'banana' 'cherry']
['banana' 'cherry' 'apple']
['apple' 'banana' 'cherry']


In [1]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

vector=arr.reshape(-1)
vector.sort()

arr2=vector.reshape(2,3)
print(arr2)

NameError: ignored

In [ ]:
x=np.array([1,2,3,4])
print (np.std(x))
std = np.sqrt(np.mean(abs(x - x.mean())**2))
print(std)

1.118033988749895
1.118033988749895


In [ ]:
print (np.var([1,2,3,4]))

1.25


In [2]:
import numpy as np
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [3]:
import numpy as np
a=[[1,0],[0,1]]
b=[1,2]
print (np.matmul(a,b))
print (np.matmul(b,a))

[1 2]
[1 2]


In [ ]:
import numpy as np

x=np.array([4.1,12.2,20.3,28.2,38.1,45.2])
y=np.array([1.0276,1.1013,1.1801,1.2652,1.3480,1.4120])

xi = 15
yi = np.interp(xi, x, y)

print(xi,yi)

15 1.1285395061728394


In [ ]:
a=np.array([[1,2,3,4,5],[-1,-2,3,8,7]])
np.save('var_a',a)

In [ ]:
b = np.load('var_a.npy')
print (b)

[[ 1  2  3  4  5]
 [-1 -2  3  8  7]]


In [ ]:
a = np.array([1,2,3,4,5])
np.savetxt('a.txt',a)
b = np.loadtxt('a.txt')
print (b)

[1. 2. 3. 4. 5.]


In [ ]:
!cat a.txt

1.000000000000000000e+00
2.000000000000000000e+00
asdasd
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00


In [ ]:
from mat4py import savemat
a={'a':100}
savemat('datafile.mat', a)

In [ ]:
from mat4py import loadmat
data = loadmat('datafile.mat')
print(data)

{'a': 100}


In [4]:
!pip install matlab

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for matlab: filename=matlab-0.1-py3-none-any.whl size=1180 sha256=37ce4f871697b3010a0d6b24e4f2ca5cdd4fcf85d882ada8ec9ab0c99398793a
  Stored in directory: /root/.cache/pip/wheels/67/e4/81/3713ad26a6b4c61b830ca8b7e839b914e684ed6bf1878e4594
Successfully built matlab


In [5]:
import matlab

print(matlab.cos(np.pi))

x=np.array([1,2,3,4])
y=np.array([1,2,3,4])
xi=1.5
print(matlab.interp(xi,x,y))

-1.0
1.5
