<a href="https://colab.research.google.com/github/jcjimenezb123/ProgramacionPython/blob/master/SENL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def g(x):
  x1,x2,x3=x #se separan los tres valores de x
  g1=np.cos(x2*x3)/3+1/6
  g2=np.sqrt(x1**2+np.sin(x3)+1.06)/9-0.1
  g3=-np.exp(-x1*x2)/20+(10*np.pi-3)/60
  return np.array([g1,g2,g3])

In [7]:
x=np.array([0.1,0.2,-0.3])

array([0.49993692, 0.04580608, 0.42473077])

In [12]:
def pfm(g,x,imax=100,tol=1e-8):
  cumple=False
  k=0 #cuenta el numero de iteraciones
  while (not cumple and k<imax):
    x0=x.copy() #se obtiene una copia de los valores iniciales
    x=g(x0) #se calcual el vector de g
    norma=np.linalg.norm(x-x0) #calcula la norma de la diferencia
    print(x,norma)
    cumple=norma<tol #se valida el criterio de conververgencia
    k+=1 #cuenta cada iteracion

  return x

In [13]:
x=np.array([0,0,0])
sol=pfm(g,x)
sol

[0.5        0.01439589 0.42359878] 0.6554717113273326
[0.4999938  0.04576507 0.42395738] 0.031371225662540796
[0.49993726 0.04577865 0.4247299 ] 0.0007747022272973615
[0.49993699 0.04580606 0.4247301 ] 2.741559434220079e-05
[0.49993692 0.04580606 0.42473077] 6.734057807872749e-07
[0.49993692 0.04580608 0.42473077] 2.2616408820907023e-08
[0.49993692 0.04580608 0.42473077] 5.558380325753473e-10


array([0.49993692, 0.04580608, 0.42473077])

In [14]:
def nrm(F,J,x,imax=100,tol=1e-8):
  cumple=False
  k=0
  while(not cumple and k<imax):
    deltax=np.linalg.solve(J(x),-F(x))
    x=x+deltax
    cumple=np.linalg.norm(F(x))<tol
    k+=1

  return x

In [15]:
def F(x):
  x1,x2=x
  f1=2*x1-x2-np.exp(-x1)
  f2=-x1+2*x2-np.exp(-x2)
  return np.array([f1,f2])

In [16]:
def J(x):
  x1,x2=x
  df1x1=2+np.exp(-x1)
  df1x2=-1
  df2x1=-1
  df2x2=2+np.exp(-x2)
  return np.array([[df1x1,df1x2],[df2x1,df2x2]])

In [17]:
x=np.array([0,0])
sol=nrm(F,J,x)
sol

array([0.56714329, 0.56714329])